[package]
name = "html_escape"
version = "0.1.0"
edition = "2024"

[dependencies]
blastview = { path = "../../crates/blastview" }
blaster = { path = "../../crates/blaster" }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.20"
