[package]
name = "blastview"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
tracing = "0.1.41"
uuid = { version = "1.18.1", features = ["v4"] }
tokio = { version = "1.47.1", features = [] }
serde = { version = "1.0.225", features = ["derive"] }
flume = "0.11.1"
